user www-data;
worker_processes auto;
pid /run/nginx.pid;
load_module /usr/lib/nginx/modules/ngx_stream_module.so;

events {
        worker_connections 2048;
}

stream {
    upstream k3s-server {
        least_conn;
        server tribus1.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
        server tribus2.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
        server tribus3.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 6443;
        proxy_pass k3s-server;
    }

    upstream ingress {
        least_conn;
        # could also add k3s-servers to this but i just leave it out so control planes can focus on important things
        server tribus4.uvm.sdu.dk:443 max_fails=3 fail_timeout=5s;
        server tribus5.uvm.sdu.dk:443 max_fails=3 fail_timeout=5s;
        server tribus6.uvm.sdu.dk:443 max_fails=3 fail_timeout=5s;
        server tribus7.uvm.sdu.dk:443 max_fails=3 fail_timeout=5s;
        server tribus8.uvm.sdu.dk:443 max_fails=3 fail_timeout=5s;
        server tribus9.uvm.sdu.dk:443 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 443;
        proxy_pass ingress;
    }
}