user www-data;
worker_processes auto;
pid /run/nginx.pid;
load_module /usr/lib/nginx/modules/ngx_stream_module.so;

events {
        worker_connections 2048;
}

stream {
    upstream k3s-server {
        least_conn;
        server bds-g00-n1.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
        server bds-g00-n2.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
        server bds-g00-n3.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 6443;
        proxy_pass k3s-server;
    }

    upstream ingress {
        least_conn;
        # could also add k3s-servers to this but i just leave it out so control planes can focus on important things
        server bds-g00-n4.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
        server bds-g00-n5.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
        server bds-g00-n6.uvm.sdu.dk:6443 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 443;
        proxy_pass ingress;
    }
}