kubernetes:
  children:
    master:
      hosts:
        bds-g00-n1:
          ansible_host: bds-g00-n1
        bds-g00-n2:
          ansible_host: bds-g00-n2
        bds-g00-n3:
          ansible_host: bds-g00-n3
    worker:
      hosts:
        bds-g00-n4:
          ansible_host: bds-g00-n4
        bds-g00-n5:
          ansible_host: bds-g00-n5
        bds-g00-n6:
          ansible_host: bds-g00-n6