kubernetes:
  children:
    master:
      hosts:
        bds-g00-n00:
          ansible_host: bds-g00-n00.uvm.sdu.dk
        # tribus2:
        #   ansible_host: tribus2.uvm.sdu.dk
        # tribus3:
        #   ansible_host: tribus3.uvm.sdu.dk
    worker:
      hosts:
        bds-g00-n01:
          ansible_host: bds-g00-n01.uvm.sdu.dk
        # tribus5:
        #   ansible_host: tribus5.uvm.sdu.dk
        # tribus6:
        #   ansible_host: tribus6.uvm.sdu.dk
        # tribus7:
        #   ansible_host: tribus7.uvm.sdu.dk
        # tribus8:
        #   ansible_host: tribus8.uvm.sdu.dk
        # tribus9:
        #   ansible_host: tribus9.uvm.sdu.dk
