- name: Build Kubernetes cluster
  hosts:
    - master
    - worker
  vars:
    k3s_become: true
    k3s_release_version: "v1.28.1+k3s1"
    k3s_etcd_datastore: true
    k3s_install_hard_links: true
    k3s_registration_address: tribus0.uvm.sdu.dk
    k3s_state: installed
  roles:
    - role: xanmanning.k3s
